// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    owner,
    balence,
    currency
) VALUES (
    $1, $2, $3
) RETURNING id, owner, balence, currency, created_at
`

type CreateAccountParams struct {
	Owner    string `json:"owner"`
	Balence  int64  `json:"balence"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Owner, arg.Balence, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balence,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
